package com.sample
 
import com.sample.DroolsTest;
import com.sample.Message;
 
rule "1"
    when
        m : Message( a1 == true )
    then
    	m.setA1(false);
    	
    	System.out.println("rule--1");
    	m.setA2(true);
        update( m );
end
rule "2"
    when
        m : Message( a2 == true )
    then
    	m.setA2(false);
    	
    	System.out.println("rule--2");
    	m.setA3(true);
        update( m );
end

query "query1"
	m:Message( a3==true )
	//System.out.println("query--2");
end